### ISSUE TITLE
Why Import database, rather than Open

### ISSUE THREAD

**Issue by processor286** [arsvechkarev/Vault#49]
This states it is kdbx compatible, so why is it offering to "import" my passwords, rather than just opening the file?

If I import and save, will I now have a "Vault" format file, rather than my original .kdbx?

**Comment by arsvechkarev** [comment]
Hi! The app imports passwords into its internal memory, and any changes to them will **not** be applied to the original file. Vault does not use any internal format, and you can export your passwords in _.kdbx_ at any time. I realize that other KeePass-compatible password managers work directly with the file, but I wanted to make Vault more simple, I wanted user not to think about files and folders when starting using the app. 

Right now there is an auto-backup feature that periodically backups your passwords to the file system, you can enable it in the settings. In the future I'm planning to improve this feature so that it can record changes history and use just one file instead of many. It should be pretty much the same as having a single file to read from and write to, but it would be optional in case user does not care about it. ;)

**Comment by processor286** [comment]
Thank you for the explanation.
